drop table if exists Recensione;
drop table if exists Videogioco;
drop table if exists Commento;
drop table if exists Utente;

CREATE TABLE Videogioco(
    titolo VARCHAR(100) PRIMARY KEY,
    rilascio DATE NOT NULL,
    casaProduttrice VARCHAR(50) NOT NULL,
    imgLocandina VARCHAR(100) NOT NULL,
    imgBanner VARCHAR(100),
    trama TEXT NOT NULL,
    piattaformaV VARCHAR(100) NOT NULL,
    genereV VARCHAR(100) NOT NULL
);

CREATE TABLE Recensione(
    idRecensione VARCHAR(30) PRIMARY KEY,
    voto INTEGER NOT NULL,
    contenuto TEXT NOT NULL,
    titolo VARCHAR(200) NOT NULL,
    dataPubblicazione DATE NOT NULL,
    idVideogioco VARCHAR(100) NOT NULL,
    FOREIGN KEY(idVideogioco) REFERENCES Videogioco(titolo) on update cascade on delete cascade
);

CREATE TABLE Utente(
    email VARCHAR(100) PRIMARY KEY,
    nickname VARCHAR(30) UNIQUE NOT NULL,
    password VARCHAR(30) NOT NULL,
    dataIscrizione DATE NOT NULL,
    imgProfilo VARCHAR(100)
);

CREATE TABLE Commento(
    idCommento VARCHAR(30) PRIMARY KEY,
    data DATE NOT NULL,
    voto INTEGER NOT NULL,
    contenuto VARCHAR(900) NOT NULL,
    idUtente VARCHAR(100) NOT NULL,
    idVideogioco VARCHAR(100) NOT NULL,
    FOREIGN KEY(idUtente) REFERENCES Utente(email) on update cascade on delete cascade,
    FOREIGN KEY(idVideogioco) REFERENCES Videogioco(titolo) on update cascade on delete cascade
);

INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("Assassin's Creed 2","2009-11-19","Ubisoft","Locandine/locandina Assassin's Creed 2.jpeg","","In seguito agli eventi del primo capitolo, Desmond Miles viene salvato dall'Abstergo dall'assassina sotto copertura Lucy Stillman e viene portato in un rifugio dove incontra la sua squadra, composta dallo storico e analista Shaun Hastings e dal tecnico Rebecca Crane...","PlayStation 3 | PlayStation 4 | XBox 360 | XBox One | Nintendo Switch | PC","Avventura | Stealth");
INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("Assassin's Creed 4 Black Flag","2013-11-29","Ubisoft","Locandine/locandina Assassin's Creed Black Flag.jpg","","Edward James Kenway è un ex corsaro della marina britannica che ha deciso di trasferirsi nei Caraibi in cerca di fortuna e avventura, abbandonando la moglie Caroline Scott in Galles e promettendole che sarebbe tornato dopo 2 anni...","PlayStation 3 | PlayStation 4 | XBox 360 | XBox One | PC","Avventura | Stealth");
INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("Assassin's Creed Odyssey","2018-10-05","Ubisoft","Locandine/locandina Assassin's Creed Odyssey.jpg","","Mesi dopo la sua avventura in Egitto, Layla Hassan è ormai un'agente degli Assassini; durante una campagna di ricerche, rinviene la lancia appartenuta al re di Sparta Leonida, spezzatasi dopo la battaglia delle Termopili, e vi riconosce un manufatto della Prima Civilizzazione; con l'aiuto di Victoria Bibeau, Layla estrae il DNA di due fratelli vissuti nel V secolo a.C., Alexios e Kassandra (segue la scelta del giocatore con quale dei due fratelli giocare)...","PlayStation 4 | XBox One | PC","Azione | Stealth");
INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("Assassin's Creed Origins","2017-10-27","Ubisoft","Locandine/locandina Assassin's Creed Origins.jpg","","Nel presente, Layla Hassan, ricercatrice dell'Abstergo, ha messo a punto una versione modificata dell'Animus, che consente a chi la usa di non necessitare dello stesso corredo genetico del soggetto di cui rivive i ricordi; contravvenendo agli ordini di Sophia Rikkin, la donna si reca in Egitto dove, invece di rintracciare un artefatto della Prima Civilizzazione, localizza la tomba di due Assassini e, coadiuvata in remoto dall'amica e collega Deanna, sperimenta il macchinario, rivivendo le loro memorie...","PlayStation 4 | XBox One | PC","Azione | Stealth");
INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("Far Cry 3","2012-11-29","Ubisoft","Locandine/locandina Far Cry 3.webp","","Il gioco è ambientato interamente nel vastissimo arcipelago di Rook Islands presumibilmente in Indonesia, da anni sconvolto da una guerra civile tra le tribù indigene e i mercenari guidati dal signore della guerra Hoyt Volker e i sanguinari pirati dal folle Vaas Montenegro, suo collaboratore gestente l'isola a nord...","PlayStation 3 | PlayStation 4 | XBox 360 | XBox One | PC","Azione | Avventura | Sparatutto");
INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("Far Cry 4","2014-11-18","Ubisoft","Locandine/locandina Far Cry 4.webp","","Il giocatore veste i panni di Ajay Ghale: un giovane ragazzo tornato nel Kyrat per esaudire l'ultimo desiderio della madre Ishwari, ossia spargere le sue ceneri a Lakshmana...","PlayStation 3 | PlayStation 4 | XBox 360 | XBox One | PC","Azione | Avventura | Sparatutto");
INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("Far Cry 5","2018-03-27","Ubisoft","Locandine/locandina Far Cry 5.jpeg","","Il gioco comincia con un breve filmato introduttivo che registra il paesaggio ambientale del Montana, per poi soffermarsi su una chiesa circondata da uomini armati, in attesa che cominci qualcosa. Dopo essere entrato nella chiesa, il personaggio continua a filmare di nascosto il discorso di Joseph Seed, fino a quando non viene scoperto e ucciso da quest'ultimo. A questo punto il segnale del video si interrompe e il protagonista si rimette il telefono in tasca...","PlayStation 4 | XBox One | PC","Azione | Avventura | Sparatutto");
INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("Ghost Recon Wildlands","2017-03-07","Ubisoft","Locandine/locandina Ghost Recon Wildlands.jpg","","Il gioco è ambientato in Bolivia nel luglio 2019. A seguito dell'aumento del potere e dell'influenza del Santa Blanca, un cartello della droga Boliviano, il paese è entrato in uno stato di grave instabilità politica al punto di diventare un narco-stato amministrato dal cartello, che lo ha trasformato nel più grande produttore di cocaina del mondo...","PlayStation 4 | XBox One | PC","Azione | Sparatutto");
INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("God Of War Ragnarok","2022-11-09","Santa Monica Studio","Locandine/locandina God Of War Ragnarok.jpeg","","Ambientato tre anni dopo gli eventi del precedente capitolo, Kratos e Atreus sopravvivono al Fimbuwinter insieme a Mimir. Atreus, dopo aver scoperto di essere un gigante, desidera esplorare il mondo alla ricerca di risposte circa la sua identità Jotunn di Loki, tuttavia Kratos glielo impedisce per timore di una guerra contro Asgard. Di ritorno da una battuta di caccia, i tre riescono a fuggire da un attacco di Freya, (la quale è in cerca di vendetta per la morte del figlio Baldur), grazie a un incantesimo di protezione lanciato da Atreus...","PlayStation 4 | PlayStation 5","Avventura");
INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("God of War","2018-04-21","Santa Monica Studio","Locandine/locandina God Of War.jpeg","","La serie di God of War è ambientata sulla Terra nei tempi antichi ed è abitata da divinità e creature mitologiche. Ogni regione del mondo è governata dagli Dei locali come sovrani e in tale zona vivono personaggi e creature della suddetta mitologia. Fino a God of War: Ascension la serie è ambientata nell'Antica Grecia dove a governarla sono gli Dei Olimpici guidati da Zeus...","PlayStation 4 | PlayStation 5 | PC","Avventura");
INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("Grand Theft Auto V","2014-11-18","Rockstar Games","Locandine/locandina Grand Theft Auto 5.webp","Banner/banner_gtav.jpeg","North Yankton, 2004. Nella cittadina di Ludendorff, Trevor Philips, Michael Townley e Bradley Snider effettuano una rapina presso un deposito locale ma le cose non vanno come previsto. Durante la fuga, Michael e Brad vengono colpiti da un cecchino, mentre Trevor scompare nella nebbia inseguito dalla polizia. Nel 2013, si scopre che Michael è ancora vivo e si è fatto una nuova vita a Los Santos (controparte di Los Angeles) e che frequenta regolarmente uno psicologo, con il quale si sfoga della sua difficile situazione familiare...","PlayStation 3 | PlayStation 4 | XBox 360 | XBox One | PC","Azione");
INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("Marvel's Spider-Man Miles Morales","2020-11-12","Insomniac Games","Locandine/locandina Marvel's SpiderMan Miles Morales.webp","","Un anno dopo gli eventi di Spider-Man, e dopo essere stato addestrato da Peter Parker (come visto nella scena finale del DLC Silver Lining), Miles Morales si è trasferito ad Harlem insieme alla madre (dopo la morte del padre avvenuta nel capitolo precedente), che nel frattempo si è candidata come sindaco della città. Miles è diventato un subalterno dello Spider-man originale, e spesso lo segue in missione, anche se molti lo ritengono un semplice assistente...","PlayStation 4 | PlayStation 5 | PC","Avventura stealth");
INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("Marvel's Spider-Man","2018-09-07","Insomniac Games","Locandine/locandina Marvel's SpiderMan.jpg","","Peter Parker, alias Spider-Man, con l'aiuto dell'agente di polizia Yuri Watanabe riesce a far arrestare il criminale Wilson Fisk, il quale, ora che la polizia ha abbastanza prove riguardo ai crimini e alle azioni illecite da lui commesse, viene arrestato e rinchiuso nel Raft, un carcere di massima sicurezza dove sono rinchiusi altri nemici dell'Arrampicamuri, tra cui Max Dillon / Electro, Adrian Toomes / Avvoltoio, MacDonald 'Mac' Gargan / Scorpion e Aleksei Sytsevich / Rhino. In seguito all'arresto di Fisk, Peter inizia a indagare su un'irruzione in una casa d'aste dove sono conservate alcune opere d'arte appartenenti a Fisk; qui incontra la sua ex ragazza Mary Jane Watson, anche lei infiltratasi per denunciare pubblicamente le azioni di Fisk...","PlayStation 4 | PlayStation 5 | PC","Avventura stealth");
INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("The Last of Us Parte 1","2013-06-14","Naughty Dog","Locandine/locandina The Last of Us Parte 1.jpg","","Nel 2013 un'epidemia generata dal fungo Cordyceps mutato si scatena negli Stati Uniti d'America, trasformando gli esseri umani in creature aggressive. Nei sobborghi di Austin Joel Miller sfugge al caos insieme a suo fratello Tommy e alla figlia tredicenne Sarah. Tuttavia, durante la fuga, Sarah viene colpita da un soldato e muore tra le braccia di Joel, che rimarrà inevitabilmente e profondamente segnato dall’accaduto...","PlayStation 3 | PlayStation 4 | PlayStation 5","Avventura | Horror | Stealth");
INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("The Last of Us Parte 2","2020-06-19","Naughty Dog","Locandine/locandina The Last of Us Parte 2.jpeg","","In seguito agli eventi del primo capitolo, Joel Miller confessa a suo fratello Tommy di aver impedito alle Luci di effettuare l'intervento che avrebbe trovato una cura per l'epidemia legata al fungo Cordyceps che sta martoriando il mondo, la quale avrebbe però portato alla morte di Ellie. Quattro anni dopo, Joel ed Ellie si sono stabiliti a Jackson, nel Wyoming, sebbene lentamente allontanandosi l'uno dall'altra...","PlayStation 4 | PlayStation 5","Avventura | Horror | Stealth");
INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("Uncharted: Drake's Fortune","2007-12-07","Naughty Dog","Locandine/locandina Uncharted 1.jpg","","Al largo delle coste di Panama, Nathan 'Nate' Drake recupera dal fondo dell'oceano la bara dell'esploratore e corsaro inglese, nonché suo antenato, Sir Francis Drake. L'evento è ripreso dalla giornalista Elena Fisher, la cui compagnia ha finanziato l'impresa per avere un buon documentario. Nella bara però non sono presenti le spoglie di Sir Francis, ma solo il suo diario (la cui ultima pagina è stata strappata) contenente la locazione di El Dorado. In quel momento, i due vengono attaccati da dei pirati, ma in loro soccorso arriva Victor Sullivan detto 'Sully', amico di Nathan...","PlayStation 3","Avventura dinamica");
INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("Uncharted 2: Il Covo dei Ladri","2009-10-14","Naughty Dog","Locandine/locandina Uncharted 2.jpg","","Due anni dopo la scoperta di El Dorado, Nathan Drake rincontra un suo vecchio amico, Harry Flynn e la sua ragazza (e vecchia fiamma di Nate) Chloe Frazer. Gli raccontano che il cliente di Flynn, Zoran Lazarevic, vuole che recuperi una lampada ad olio da un museo. Nate all'inizio rifiuta, ma accetta quando scopre che potrebbe celare la risposta al destino delle navi perdute di Marco Polo. Inoltre Nate e Chloe pianificano di scappare insieme dopo aver rinvenuto il tesoro all'insaputa di Flynn...","PlayStation 3","Avventura dinamica");
INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("Uncharted 3: L'Inganno di Drake","2011-11-02","Naughty Dog","Locandine/locandina Uncharted 3.jpg","","In un pub di Londra, Nathan Drake e il suo mentore Victor Sullivan hanno intenzione di vendere l'anello di Sir Francis Drake a un uomo di nome Talbot. Tuttavia, l'affare va a monte poiché i due scoprono che il denaro è falso e Talbot, per tutta risposta, sguinzaglia i suoi uomini. Scappando, vengono fermati e uccisi da Charlie Cutter, un buttafuori al servizio della perfida Katherine Marlowe, che sottrae l'anello a Drake e fugge insieme a Talbot...","PlayStation 3","Avventura dinamica");
INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("Uncharted 4: Fine di un Ladro","2016-05-10","Naughty Dog","Locandine/locandina Uncharted 4.jpg","","Il gioco inizia con Nathan 'Nate' Drake che, nel bel mezzo di una tempesta, sta guidando una barca inseguito da mercenari che tentano di uccidere lui e Samuel 'Sam' Drake, fratello di Nate, che si trova sulla barca con lui. Il duo sta cercando di raggiungere un'isola ma all'improvviso una nave in fiamme dei mercenari colpisce la barca e Nate e Sam finiscono per essere travolti in mare...","PlayStation 4","Avventura dinamica");
INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("Watch Dogs","2014-05-27","Ubisoft","Locandine/locandina WatchDogs 1.webp","","Nel 2012, Chicago diventa la prima città al mondo ad implementare il ctOS (central Operating System) - una rete informatica che collega ogni dispositivo in un unico sistema, sviluppato dalla società tecnologica Blume. Durante una rapina elettronica all'hotel di lusso Merlaut, l'hacker Aiden Pearce e il suo mentore e partner, Damien Brenks, fanno scattare un allarme silenzioso impostato da un altro hacker. Damien cerca di trovare l'hacker, consegnando se stesso e Aiden. Temendo per la sua famiglia, Aiden li porta al sicuro con la scusa di un viaggio a sorpresa in campagna...","PlayStation 3 | PlayStation 4 | XBox 360 | XBox One | PC","Avventura dinamica | Stealth");
INSERT INTO Videogioco(titolo,rilascio,casaProduttrice,imgLocandina,imgBanner,trama,piattaformaV,genereV) VALUES("Watch Dogs 2","2016-11-15","Ubisoft","Locandine/locandina WatchDogs 2.jpg","","Nel 2016, tre anni dopo gli eventi del titolo precedente, San Francisco diventa la prima città a installare una versione migliorata del ctOS, una rete che collega ogni dispositivo elettronico in un singolo sistema, sviluppata dalla compagnia Blume. L'hacker Marcus Holloway, che in passato era stato incarcerato da questo 'ctOS 2.0' per un crimine da lui non commesso, decide di unirsi al gruppo di hacker DedSec (composto dai giovani hacker Sitara Dhawana, Josh Sauchak, Horatio Carlin e 'Wrench') e intraprende una sorta di iniziazione hackerando una server farm della Blume e cancellando il proprio profilo dal sistema...","PlayStation 4 | XBox One | PC","Avventura dinamica | Stealth");